fix(tests): Lock Babel 7 deps to 7.0.0-beta.2, Fix Linting Errors
An unknown change added to the latest Babel 7 beta caused optional chaining to break when running tests directly from the command line in AVA. Locking all ^7.0.0-beta.0 dependencies to 7.0.0-beta.2 corrected the error. Stack trace for future reference:

 TypeError: Cannot read property 'loose' of undefined
    at _default (D:\GitHub\Flickr-Wormhole\node_modules\babel-plugin-transform-optional-chaining\lib\index.js:12:31)
    at Function.memoisePluginContainer (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
    at Function.normalisePlugin (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\GitHub\Flickr-Wormhole\node_modules\ava\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at CachingPrecompiler._transform (D:\GitHub\Flickr-Wormhole\node_modules\ava\lib\caching-precompiler.js:58:24)
    at transform (D:\GitHub\Flickr-Wormhole\node_modules\caching-transform\index.js:43:10)
    at CachingPrecompiler.transform (D:\GitHub\Flickr-Wormhole\node_modules\caching-transform\index.js:60:17)
    at CachingPrecompiler.precompileFile (D:\GitHub\Flickr-Wormhole\node_modules\ava\lib\caching-precompiler.js:39:9)
    at Api._runFile (D:\GitHub\Flickr-Wormhole\node_modules\ava\api.js:58:33)
From previous event:
    at Api._runWithPool (D:\GitHub\Flickr-Wormhole\node_modules\ava\api.js:243:5)
    at _setupPrecompiler.then.then (D:\GitHub\Flickr-Wormhole\node_modules\ava\api.js:174:17)
    at <anonymous>


In addition, made some minor changes to empty tests to satisfy linting rules, and made some minor configuration changes for babel/ava/wallaby/travis.